FROM node

# copying the rest of the code
COPY .  /usr/src/app

# going into the app dir
RUN cd usr/src/app && npm install

# setting the default workspace
WORKDIR /usr/src/app

EXPOSE 3000

CMD [ "npm", "start" ]