# Generated by Django 4.2.6 on 2023-10-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attack_priority', models.IntegerField()),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=5)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=5)),
                ('enemy_organization', models.CharField(max_length=100)),
                ('target_goal', models.CharField(max_length=100)),
                ('was_target_destroyed', models.BooleanField(null=True)),
                ('target_id', models.IntegerField()),
            ],
        ),
    ]
