apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: ghcr.io/expruc/kubernetes-gradutaion-drill/k8s-final-drill:backend
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: backend-config
          resources:
            limits:
              memory: "50Mi"   
              cpu: "10m"       
            requests:
              memory: "16Mi"  
              cpu: "1m"       
          readinessProbe: 
            tcpSocket:
              port: 3000 
            initialDelaySeconds: 5 
            periodSeconds: 10      