# Generated by Django 4.2.6 on 2023-10-17 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('tz', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(limit_value=999999999)])),
                ('date_of_birth', models.DateField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
