# Generated by Django 4.2.6 on 2023-10-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_parent_kids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='kids',
            field=models.ManyToManyField(default=[], related_name='child', to='people.person'),
        ),
    ]
