# Generated by Django 4.2.6 on 2023-10-19 13:18

from django.db import migrations, models
from people.models import Parent
from django.db.models import F
import math


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_parent_kids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='salary',
            field=models.PositiveIntegerField(max_length=6, null=True),
        ),
    ]

    def round_salary_to_int(apps, schema_editor):
        model = apps.get_model('people', 'Parent')

        for parent in model.objects.all():
            parent.salary = math.ceil('salary')
            parent.save()
    


